[project]
name = ""
version = "0.0.1"
author = ""
description = ""
license = ""
love_version = ""
lua_version = "5.4"
source_dir = "src"
build_dir = "build"
entry = "main.lua"
amor_version = "0.5.0"

[build]
include = [ "*.png",]

[scripts]
test = "echo \"Hello, World!\""
build = "echo \"No build script defined!\""

[dependencies.zip]
src = "https://github.com/matiasah/zip.git"

[dependencies.luafilesystem]
src = "https://github.com/lunarmodules/luafilesystem.git"
