[project]
name = ""
version = "0.0.1"
author = ""
description = ""
license = ""
love_version = ""
lua_version = "5.4"
source_dir = "src"
build_dir = "build"
entry = "main.lua"

[scripts]
test = "echo \"Hello, World!\""
build = "echo \"No build script defined!\""

[dependencies]
zip = "zip:matiasah/zip@None=f7808d24127e7ea8458c6045b61a69295e102ec5"
lfs = "lfs:lunarmodules/luafilesystem@None=09511782201302ade916d4b250d01a6c61b56844"

[dev_dependencies]
