#!/bin/bash

printf '\n\e[1;92m%-6s \e[1;52;49;91m❤\e[m\n' "building amor..."

pyinstaller src/main.py --clean -n amor

printf '\n\e[1;92m%-6s \e[1;52;49;91m❤\e[m\n' "amor built!"
printf '\n\e[93m%-6s\e[m\n' "Add the following path to your system PATH:"
relative_path="dist/amor"
absolute_path="$(pwd)/${relative_path}"
printf "\n$absolute_path\n"

printf '\n\e[93m%-6s\e[m\n' "Add the following to your system LUA_PATH:"
printf "\n./.amor/?/init.lua;./.amor/?/?.lua;\n"

printf '\n\e[93m%-6s\e[m\n' "Add the following to your system LUA_CPATH:"
printf "\n./.amor/?/?.so;\n\n"
