#!/bin/bash

if ! python_loc="$(type -p "python3")" || [[-z $python_loc]]; then
    printf '\n\e[1;33m%-6s\e[m\n' "Python 3 not installed!"
    printf "\nVisit \e]8;;www.python.org/downloads\e\\www.python.org/downloads\e]8;;\e\\ to get started.\n"
    exit 1
else
    printf '\n\e[1;92m%-6s\e[m\n\n' "Python 3 found!"
fi

if ! luarocks_loc="$(type -p "luarocks")" || [[-z $luarocks_loc]]; then
    printf '\n\e[1;33m%-6s\e[m\n' "Luarocks not installed!"
    printf "\nVisit \e]8;;https://luarocks.org/\e\\https://luarocks.org/\e]8;;\e\\ to get started.\n"
    exit 1
else
    printf '\n\e[1;92m%-6s\e[m\n\n' "Luarocks found!"
fi

if ! git_loc="$(type -p "git")" || [[-z $git_loc]]; then
    printf '\n\e[1;33m%-6s\e[m\n' "Git not installed!"
    printf "\nVisit \e]8;;https://git-scm.com/downloads\e\\https://git-scm.com/downloads\e]8;;\e\\ to get started.\n"
    exit 1
else
    printf '\n\e[1;92m%-6s\e[m\n\n' "Git found!"
fi

python3 -m pip install -r requirements.txt

printf '\n\e[1;92m%-6s \e[1;52;49;91m❤\e[m\n' "building amor..."

pyinstaller src/main.py --clean -n amor

printf '\n\e[1;92m%-6s \e[1;52;49;91m❤\e[m\n' "amor built!"
printf '\n\e[93m%-6s\e[m\n' "Add the following path to your system PATH:"
relative_path="dist/amor"
absolute_path="$(pwd)/${relative_path}"
printf "\n$absolute_path\n"

printf '\n\e[93m%-6s\e[m\n' "Add the following to your system LUA_PATH:"
printf "\n./.amor/?/init.lua;./.amor/?/?.lua;\n"

printf '\n\e[93m%-6s\e[m\n' "Add the following to your system LUA_CPATH:"
printf "\n./.amor/?/?.so;\n\n"
