#!/bin/bash

if ! command -v python3 >/dev/null 2>&1; then
    printf '\n\e[1;33m%-6s\e[m\n' "Python 3 not installed!"
    printf "\nVisit \e]8;;www.python.org/downloads\e\\www.python.org/downloads\e]8;;\e\\ to get started.\n"
    exit 1
else
    printf '\n\e[1;92m%-6s\e[m\n\n' "Python 3 found!"
fi

if ! command -v luarocks >/dev/null 2>&1; then
    printf '\n\e[1;33m%-6s\e[m\n' "Luarocks not installed!"
    printf "\nVisit \e]8;;https://luarocks.org/\e\\https://luarocks.org/\e]8;;\e\\ to get started.\n"
    exit 1
else
    printf '\n\e[1;92m%-6s\e[m\n\n' "Luarocks found!"
fi

if ! command -v git >/dev/null 2>&1; then
    printf '\n\e[1;33m%-6s\e[m\n' "Git not installed!"
    printf "\nVisit \e]8;;https://git-scm.com/downloads\e\\https://git-scm.com/downloads\e]8;;\e\\ to get started.\n"
    exit 1
else
    printf '\n\e[1;92m%-6s\e[m\n\n' "Git found!"
fi

if ! command -v lua >/dev/null 2>&1; then
    printf '\n\e[1;33m%-6s\e[m\n' "Lua not installed!"
    printf "\nVisit \e]8;;https://www.lua.org/download.html\e\\https://www.lua.org/download.html\e]8;;\e\\ to get started.\n"
    exit 1
else
    printf "\n\e[1;92m%-6s \e[1;52;49;91m❤\e[m\n\n" "Lua found!"
fi

if ! command -v love >/dev/null 2>&1; then
    printf '\n\e[1;33m%-6s\e[m\n' "Löve2D not installed!"
    printf "\nVisit \e]8;;https://love2d.org/\e\\https://love2d.org/\e]8;;\e\\ to get started.\n"
    printf "\n\e[1;93m%-6s\e[m\n" "Löve is not required, but it certainly helps ;)"
else
    printf "\n\e[1;92m%-6s \e[1;52;49;91m❤\e[m\n\n" "Löve2D found!"
fi

python3 -m pip install -r requirements.txt

printf '\n\e[1;92m%-6s \e[1;52;49;91m❤\e[m\n' "building amor..."

if ! pyinstaller src/main.py --clean -n amor; then
    printf "\n\e[1;91mSomething went wrong!\e[m\n"
    printf "\n\e[93mIf you did not trigger this, check the logs. Otherwise, try again when ready.\e[m\n\n"
    exit 1
fi

printf '\n\e[1;92m%-6s \e[1;52;49;91m❤\e[m\n' "amor built!"
printf '\n\e[93m%-6s\e[m\n' "Add the following path to your system PATH:"
relative_path="dist/amor"
absolute_path="$(pwd)/${relative_path}"
printf "\n$absolute_path\n"

printf '\n\e[93m%-6s\e[m\n' "Add the following to your system LUA_PATH:"
printf "\n./.amor/?/init.lua;./.amor/?/?.lua;\n"

printf '\n\e[93m%-6s\e[m\n' "Add the following to your system LUA_CPATH:"
printf "\n./.amor/?/?.so;\n\n"
